name: pose
description: Dart library for loading, viewing, augmenting, and handling .pose files
version: 1.1.5
repository: https://github.com/bipinkrish/pose
topics:
  - pose

environment:
  sdk: ^3.0.0

dependencies:
  image: ^4.1.7
  tuple: ^2.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0